<a href="https://colab.research.google.com/github/linda-bsharat/telco-customer-churn-prediction/blob/main/notebooks/01_data_cleaning_and_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**telco-customer-churn-prediction**

In [1]:
#////////////////////////////////////
# Importing LIB
#///////////////////////////////////


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#////////////////////////////////////
# importing data
#///////////////////////////////////



url = "https://raw.githubusercontent.com/linda-bsharat/telco-customer-churn-prediction/main/data/telco_customer_data_v2.csv"
df = pd.read_csv(url)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST00001,Male,0,No,Yes,3.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,68.61,205.83,Yes
1,CUST00002,Male,1,Yes,No,2.0,Yes,Yes,DSL,No,...,No internet service,Yes,NaN,No,One year,Yes,Bank transfer (automatic),23.15,46.3,No
2,CUST00003,Female,No,No,No,42.0,Yes,Yes,DSL,No,...,No,NaN,Yes,Yes,Month-to-month,No,Electronic check,42.63,1790.46,Yes
3,CUST00004,Female,0,No,Yes,40.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,No internet service,Month-to-month,No,Electronic check,75.04,3001.6,No
4,CUST00005,Male,Yes,Yes,Yes,17.0,Yes,NaN,Fiber optic,Yes,...,Yes,No,No internet service,No,Two year,Yes,Electronic check,22.38,380.46,Yes

## **`part 1: fix the missing values`**

In [3]:
df.isna().sum().sort_values(ascending=False).head(15)

PaymentMethod       3569
Dependents          3565
Partner             3530
OnlineSecurity      2922
DeviceProtection    2894
StreamingTV         2827
StreamingMovies     2785
OnlineBackup        2747
TechSupport         2733
MultipleLines       1868
TotalCharges        1062
gender               748
SeniorCitizen        659
tenure               567
MonthlyCharges       388
dtype: int64

In [4]:
# =========================
# Handle Missing Values
# =========================

# yes/no service columns
service_cols = [
    "Dependents",
    "Partner",
    "OnlineSecurity",
    "DeviceProtection",
    "StreamingTV",
    "StreamingMovies",
    "OnlineBackup",
    "TechSupport",
    "MultipleLines",
]

df[service_cols] = df[service_cols].fillna("No")

MISSING DATA

In [5]:
df.isna().sum().sort_values(ascending=False).head(15)

PaymentMethod       3569
TotalCharges        1062
gender               748
SeniorCitizen        659
tenure               567
MonthlyCharges       388
Dependents             0
customerID             0
Partner                0
OnlineSecurity         0
PhoneService           0
MultipleLines          0
InternetService        0
TechSupport            0
DeviceProtection       0
dtype: int64

In [6]:
# =========================
# Fix TotalCharges type
# =========================

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# =========================
# Handle numeric missing (tenure, MonthlyCharges)
# =========================

df["tenure"] = df["tenure"].fillna(df["tenure"].median())
df["MonthlyCharges"] = df["MonthlyCharges"].fillna(df["MonthlyCharges"].median())

# =========================
# Impute TotalCharges using tenure * MonthlyCharges
# =========================

mask = df["TotalCharges"].isna()

df.loc[mask, "TotalCharges"] = (
    df.loc[mask, "tenure"] * df.loc[mask, "MonthlyCharges"]
)

In [7]:
df.isna().sum().sort_values(ascending=False)

PaymentMethod       3569
gender               748
SeniorCitizen        659
Partner                0
customerID             0
Dependents             0
tenure                 0
MultipleLines          0
PhoneService           0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
InternetService        0
TechSupport            0
StreamingTV            0
Contract               0
StreamingMovies        0
PaperlessBilling       0
MonthlyCharges         0
TotalCharges           0
Churn                  0
dtype: int64

In [8]:
# =========================
# Handle demographic missing values
# =========================

df["gender"] = df["gender"].fillna(df["gender"].mode()[0])
df["SeniorCitizen"] = df["SeniorCitizen"].fillna(df["SeniorCitizen"].mode()[0])

In [9]:
df.isna().sum().sort_values(ascending=False).head(3)

PaymentMethod    3569
gender              0
SeniorCitizen       0
dtype: int64

In [10]:
df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             27841
Bank transfer (automatic)    14102
Mailed check                 13963
Credit card (automatic)      10400
BANK TRANSFER                  125
Name: count, dtype: int64

In [11]:
df[df["PaymentMethod"].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
88,CUST00089,Female,1,No,No,14.0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,NaN,37.44,524.16,Yes
90,CUST00091,Male,0,No,No,22.0,Yes,No,DSL,No,...,No,No,No internet service,No,Month-to-month,Yes,NaN,41.19,906.18,Yes
109,CUST00110,FEMALE,No,No,No,11.0,Yes,Yes,DSL,No,...,No internet service,No,No,No internet service,Two year,Yes,NaN,18.39,202.29,No
113,CUST00114,Female,0,Yes,Yes,21.0,No,No phone service,Fiber optic,No,...,No,No,No,No,Two year,No,NaN,25.91,544.11,No
159,CUST00160,Male,0,No,Yes,10.0,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,NaN,29.91,299.10,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69874,CUST69875,Male,0,No,Yes,18.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,One year,Yes,NaN,41.19,741.42,No
69901,CUST69902,Female,0,No,Yes,30.0,Yes,No,DSL,No,...,No,No,No,No,Two year,No,NaN,46.09,1382.70,No
69933,CUST69934,Female,No,Yes,Yes,35.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,NaN,41.19,1441.65,No
69936,CUST69937,Male,0,No,No,7.0,Yes,No,DSL,No,...,Yes,No,No,No,One year,Yes,NaN,29.43,206.01,Yes
69937,CUST69938,Female,1,No,No,23.0,Yes,No,Fiber optic,No,...,Yes,No internet service,No,No,Month-to-month,No,NaN,25.20,579.60,Yes

In [12]:
# =========================
# Handle PaymentMethod missing values
# =========================

df["PaymentMethod"] = df["PaymentMethod"].fillna(df["PaymentMethod"].mode()[0])

In [13]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

FIXING GENDER COLUMS

In [14]:

df['gender'] = df['gender'].str.strip().str.capitalize()
df['gender'] = df['gender'].replace({'F': 'Female', 'M': 'Male'})
df['gender'] = df['gender'].replace({ 'Man': 'Male'})

In [15]:
df["gender"].value_counts()

gender
Female    35535
Male      34465
Name: count, dtype: int64

FIXING SENIOR CITIZEN COLUMNS

In [16]:
df["SeniorCitizen"] = df["SeniorCitizen"].replace({
    "Yes": 1,
    "No": 0,
    "not senior": 0})
df["SeniorCitizen"] = df["SeniorCitizen"].astype(int)

In [17]:
df["SeniorCitizen"].value_counts()

SeniorCitizen
0    56053
1    13947
Name: count, dtype: int64

FIXING CHURN

In [18]:
df["Churn"].value_counts()

Churn
No          37057
Yes         32713
Unknown        54
CHURNED        46
N              46
NO CHURN       45
Y              39
Name: count, dtype: int64

CONVARTE DATA IN CHURN

In [19]:

pd.set_option('future.no_silent_downcasting', True)

df['Churn'] = df['Churn'].replace({
    'Yes': 1, 'Y': 1, 'CHURNED': 1,
    'No': 0, 'N': 0, 'NO CHURN': 0,
    'Unknown': None
})
df = df.dropna(subset=['Churn'])
df['Churn'] = df['Churn'].astype(int)

In [20]:
df["Churn"].value_counts()

Churn
0    37148
1    32798
Name: count, dtype: int64

In [21]:
# =========================
# Standardize PaymentMethod
# =========================

df['PaymentMethod'] = df['PaymentMethod'].replace({
    'BANK TRANSFER': 'Bank transfer (automatic)'
})

df['PaymentMethod'].value_counts()

PaymentMethod
Electronic check             31379
Bank transfer (automatic)    14215
Mailed check                 13959
Credit card (automatic)      10393
Name: count, dtype: int64

In [22]:
yes_no_columns = [
    'Partner',
    'Dependents',
    'PhoneService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'PaperlessBilling'
]

for col in yes_no_columns:
    print(f"{col} unique values:", df[col].unique())

Partner unique values: ['No' 'Yes']
Dependents unique values: ['Yes' 'No']
PhoneService unique values: ['Yes' 'No']
OnlineSecurity unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
OnlineBackup unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
DeviceProtection unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
TechSupport unique values: ['No internet service' 'Yes' 'No' 'Y' 'True']
StreamingTV unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
StreamingMovies unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
PaperlessBilling unique values: ['No' 'Yes']

In [23]:
df.replace(['Y', 'True'], 'Yes', inplace=True)

In [24]:
df.replace('No internet service', 'No', inplace=True)

In [25]:
yes_no_columns = [
    'Partner',
    'Dependents',
    'PhoneService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'PaperlessBilling'
]

for col in yes_no_columns:
    df[col] = df[col].fillna('No')

In [26]:
for col in yes_no_columns:
    print(col, df[col].unique())

Partner ['No' 'Yes']
Dependents ['Yes' 'No']
PhoneService ['Yes' 'No']
OnlineSecurity ['No' 'Yes']
OnlineBackup ['No' 'Yes']
DeviceProtection ['No' 'Yes']
TechSupport ['No' 'Yes']
StreamingTV ['No' 'Yes']
StreamingMovies ['No' 'Yes']
PaperlessBilling ['No' 'Yes']

In [27]:
for col in yes_no_columns:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [28]:
print(df[yes_no_columns].head())

   Partner  Dependents  PhoneService  OnlineSecurity  OnlineBackup  \
0        0           1             1               0             0
1        1           0             1               0             0
2        0           0             1               0             1
3        0           1             1               0             0
4        1           1             1               1             0

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0                 0            0            0                0
1                 0            1            0                0
2                 0            0            1                1
3                 1            0            0                0
4                 1            0            0                0

   PaperlessBilling
0                 0
1                 1
2                 0
3                 0
4                 1

In [29]:
print(df[yes_no_columns].dtypes)

Partner             int64
Dependents          int64
PhoneService        int64
OnlineSecurity      int64
OnlineBackup        int64
DeviceProtection    int64
TechSupport         int64
StreamingTV         int64
StreamingMovies     int64
PaperlessBilling    int64
dtype: object

## Problem **Here**

In [30]:
df['Churn'].value_counts()
df['Churn'].info()

<class 'pandas.core.series.Series'>
Index: 69946 entries, 0 to 69999
Series name: Churn
Non-Null Count  Dtype
--------------  -----
69946 non-null  int64
dtypes: int64(1)
memory usage: 1.1 MB

In [31]:
df['Churn'] = df['Churn'].replace({'Yes': 1, 'No': 0})

In [32]:
df['Churn'].value_counts()
df['Churn'].info()

<class 'pandas.core.series.Series'>
Index: 69946 entries, 0 to 69999
Series name: Churn
Non-Null Count  Dtype
--------------  -----
69946 non-null  int64
dtypes: int64(1)
memory usage: 1.1 MB

In [33]:
print(df[yes_no_columns].isnull().sum())

Partner             0
Dependents          0
PhoneService        0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
PaperlessBilling    0
dtype: int64

In [34]:
df.select_dtypes(include='object').columns

Index(['customerID', 'gender', 'MultipleLines', 'InternetService', 'Contract',
       'PaymentMethod'],
      dtype='object')

In [35]:
for col in df.select_dtypes(include='object').columns:
    print("Column:", col)
    print(df[col].unique())
    print("-"*50)

Column: customerID
['CUST00001' 'CUST00002' 'CUST00003' ... 'CUST69998' 'CUST69999'
 'CUST70000']
--------------------------------------------------
Column: gender
['Male' 'Female']
--------------------------------------------------
Column: MultipleLines
['Yes' 'No' 'No phone service']
--------------------------------------------------
Column: InternetService
['No' 'DSL' 'Fiber optic']
--------------------------------------------------
Column: Contract
['Month-to-month' 'One year' 'Two year' 'M-M']
--------------------------------------------------
Column: PaymentMethod
['Mailed check' 'Bank transfer (automatic)' 'Electronic check'
 'Credit card (automatic)']
--------------------------------------------------

In [36]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [37]:
df['gender'] = df['gender'].str.strip().str.capitalize()
df['gender'] = df['gender'].replace({'F': 'Female', 'M': 'Male'})
df['gender'] = df['gender'].replace({ 'Man': 'Male'})

In [38]:
df['gender'] = df['gender'].replace('nan', None)
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

In [39]:
print(df['gender'].isnull().sum())

0

In [40]:
print(df['gender'].unique())

['Male' 'Female']

In [41]:
df['gender'] = df['gender'].map({'Male':1, 'Female':0})

In [42]:
print("Unique values:", df['gender'].unique())
print("Missing values:", df['gender'].isnull().sum())
print("Data type:", df['gender'].dtype)

Unique values: [1 0]
Missing values: 0
Data type: int64

 DATATYPE  FOR SOME FIXING

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69946 entries, 0 to 69999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        69946 non-null  object
 1   gender            69946 non-null  int64
 2   SeniorCitizen     69946 non-null  int64
 3   Partner           69946 non-null  int64
 4   Dependents        69946 non-null  int64
 5   tenure            69946 non-null  float64
 6   PhoneService      69946 non-null  int64
 7   MultipleLines     69946 non-null  object
 8   InternetService   69946 non-null  object
 9   OnlineSecurity    69946 non-null  int64
 10  OnlineBackup      69946 non-null  int64
 11  DeviceProtection  69946 non-null  int64
 12  TechSupport       69946 non-null  int64
 13  StreamingTV       69946 non-null  int64
 14  StreamingMovies   69946 non-null  int64
 15  Contract          69946 non-null  object
 16  PaperlessBilling  69946 non-null  int64
 17  PaymentMethod     69946 non-null  object
 18  MonthlyCharges    69946 non-null  float64
 19  TotalCharges      69946 non-null  float64
 20  Churn             69946 non-null  int64
dtypes: float64(3), int64(13), object(5)
memory usage: 11.7+ MB

# **Fixing the multiple lines values                    // Qassam**

In [44]:
df["MultipleLines"].value_counts()

MultipleLines
Yes                 34660
No                  27033
No phone service     8253
Name: count, dtype: int64

In [45]:
df[(df["PhoneService"] == 1) &
   (df["MultipleLines"] == "No phone service")].shape

(1320, 21)

In [46]:
mask = (df['PhoneService'] == 1) & (df['MultipleLines'] == 'No phone service')
df.loc[mask, 'MultipleLines'] = 'No'
print(f'Fixed {mask.sum()} inconsistent rows')

Fixed 1320 inconsistent rows

In [47]:
print(df['MultipleLines'].value_counts())

MultipleLines
Yes                 34660
No                  28353
No phone service     6933
Name: count, dtype: int64

# success ///////////QASSAM

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69946 entries, 0 to 69999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        69946 non-null  object
 1   gender            69946 non-null  int64
 2   SeniorCitizen     69946 non-null  int64
 3   Partner           69946 non-null  int64
 4   Dependents        69946 non-null  int64
 5   tenure            69946 non-null  float64
 6   PhoneService      69946 non-null  int64
 7   MultipleLines     69946 non-null  object
 8   InternetService   69946 non-null  object
 9   OnlineSecurity    69946 non-null  int64
 10  OnlineBackup      69946 non-null  int64
 11  DeviceProtection  69946 non-null  int64
 12  TechSupport       69946 non-null  int64
 13  StreamingTV       69946 non-null  int64
 14  StreamingMovies   69946 non-null  int64
 15  Contract          69946 non-null  object
 16  PaperlessBilling  69946 non-null  int64
 17  PaymentMethod     69946 non-null  object
 18  MonthlyCharges    69946 non-null  float64
 19  TotalCharges      69946 non-null  float64
 20  Churn             69946 non-null  int64
dtypes: float64(3), int64(13), object(5)
memory usage: 11.7+ MB

In [49]:
df["InternetService"].value_counts()

InternetService
Fiber optic    38470
DSL            17579
No             13897
Name: count, dtype: int64

In [50]:
df["MultipleLines"].value_counts()

MultipleLines
Yes                 34660
No                  28353
No phone service     6933
Name: count, dtype: int64

FIXING CONTRACT

In [51]:
df["Contract"].value_counts()

Contract
Month-to-month    41814
One year          14005
Two year          13961
M-M                 166
Name: count, dtype: int64

In [52]:
df["Contract"] = df["Contract"].replace({
    "M-M": "Month-to-month"
})

# Verify
print(df["Contract"].value_counts())

Contract
Month-to-month    41980
One year          14005
Two year          13961
Name: count, dtype: int64

# **Feature Engineering**

In [53]:
df["HasInternet"] = (df["InternetService"] != "No").astype(int)

In [54]:
df["HasInternet"].value_counts()

HasInternet
1    56049
0    13897
Name: count, dtype: int64

In [55]:
display(df[['InternetService', 'HasInternet']].head(10))

  InternetService  HasInternet
0              No            0
1             DSL            1
2             DSL            1
3     Fiber optic            1
4     Fiber optic            1
5     Fiber optic            1
6              No            0
7     Fiber optic            1
8             DSL            1
9              No            0

# =========================
# Remove Outliers
# =========================
# tenure: impossible values (-10, 999 months)
# MonthlyCharges: extreme values up to $1,478

In [56]:
print(f"Rows before: {len(df):,}")

df = df[(df["tenure"] >= 0) & (df["tenure"] <= 100)]
df = df[df["MonthlyCharges"] <= 200]

print(f"Rows after: {len(df):,}")

Rows before: 69,946
Rows after: 67,376

# =========================
# Encode Remaining Categorical Columns
# =========================

In [57]:

df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             30263
Bank transfer (automatic)    13653
Mailed check                 13467
Credit card (automatic)       9993
Name: count, dtype: int64

In [58]:
df = pd.get_dummies(df, columns=["PaymentMethod"])

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67376 entries, 0 to 69999
Data columns (total 25 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customerID                               67376 non-null  object
 1   gender                                   67376 non-null  int64
 2   SeniorCitizen                            67376 non-null  int64
 3   Partner                                  67376 non-null  int64
 4   Dependents                               67376 non-null  int64
 5   tenure                                   67376 non-null  float64
 6   PhoneService                             67376 non-null  int64
 7   MultipleLines                            67376 non-null  object
 8   InternetService                          67376 non-null  object
 9   OnlineSecurity                           67376 non-null  int64
 10  OnlineBackup                             67376 non-null  int64
 11  DeviceProtection                         67376 non-null  int64
 12  TechSupport                              67376 non-null  int64
 13  StreamingTV                              67376 non-null  int64
 14  StreamingMovies                          67376 non-null  int64
 15  Contract                                 67376 non-null  object
 16  PaperlessBilling                         67376 non-null  int64
 17  MonthlyCharges                           67376 non-null  float64
 18  TotalCharges                             67376 non-null  float64
 19  Churn                                    67376 non-null  int64
 20  HasInternet                              67376 non-null  int64
 21  PaymentMethod_Bank transfer (automatic)  67376 non-null  bool
 22  PaymentMethod_Credit card (automatic)    67376 non-null  bool
 23  PaymentMethod_Electronic check           67376 non-null  bool
 24  PaymentMethod_Mailed check               67376 non-null  bool
dtypes: bool(4), float64(3), int64(14), object(4)
memory usage: 11.6+ MB

# =========================
# Encode Categorical Columns
# =========================

In [61]:

# MultipleLines - has order: no service < no < yes
df['MultipleLines'] = df['MultipleLines'].replace({
    'No phone service': 0, 'No': 1, 'Yes': 2
})

# InternetService - has order: no < DSL < Fiber
df['InternetService'] = df['InternetService'].replace({
    'No': 0, 'DSL': 1, 'Fiber optic': 2
})

# Contract - has order: monthly < yearly < two years
df['Contract'] = df['Contract'].replace({
    'Month-to-month': 0, 'One year': 1, 'Two year': 2
})


# Verify
print("Remaining object columns:", df.select_dtypes(include='object').columns.tolist())
print("Shape:", df.shape)

Remaining object columns: ['customerID', 'MultipleLines', 'InternetService', 'Contract']
Shape: (67376, 25)

In [62]:
print("MultipleLines:", df['MultipleLines'].unique())
print("InternetService:", df['InternetService'].unique())
print("Contract:", df['Contract'].unique())

MultipleLines: [2 1 0]
InternetService: [0 1 2]
Contract: [0 1 2]

# =========================
# Fix Column Data Types
# =========================

In [63]:
df['MultipleLines'] = df['MultipleLines'].astype(int)
df['InternetService'] = df['InternetService'].astype(int)
df['Contract'] = df['Contract'].astype(int)

print("Remaining object columns:", df.select_dtypes(include='object').columns.tolist())
print(df[['MultipleLines', 'InternetService', 'Contract']].dtypes)

Remaining object columns: ['customerID']
MultipleLines      int64
InternetService    int64
Contract           int64
dtype: object

Final Check !

In [64]:

print("=== Shape ===")
print(df.shape)

print("\n=== Missing Values ===")
print(df.isna().sum().sum(), "total missing values")

print("\n=== Churn Distribution ===")
print(df['Churn'].value_counts(normalize=True).round(3))

print("\n=== Data Types ===")
print(df.dtypes)

=== Shape ===
(67376, 25)

=== Missing Values ===
0 total missing values

=== Churn Distribution ===
Churn
0    0.531
1    0.469
Name: proportion, dtype: float64

=== Data Types ===
customerID                                  object
gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                     float64
PhoneService                                 int64
MultipleLines                                int64
InternetService                              int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
Contract                                     int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                        int64
HasInternet                                  int64
PaymentMethod_Bank transfer (automatic)       bool
PaymentMethod_Credit card (automatic)         bool
PaymentMethod_Electronic check                bool
PaymentMethod_Mailed check                    bool
dtype: object

# =========================
# Feature Engineering
# =========================

In [65]:


# 1. Is the customer new? (less than 6 months)
df['IsNewCustomer'] = (df['tenure'] <= 6).astype(int)

# 2. Is the customer long-term? (more than 48 months)
df['IsLongTermCustomer'] = (df['tenure'] >= 48).astype(int)

# 3. Average monthly charge based on total charges
df['AvgMonthlyCharge'] = df['TotalCharges'] / (df['tenure'] + 1)

# 4. Number of services subscribed
service_cols = [
    'PhoneService', 'OnlineSecurity', 'OnlineBackup',
    'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies'
]
df['TotalServices'] = df[service_cols].sum(axis=1)

print(df[['IsNewCustomer', 'IsLongTermCustomer',
          'AvgMonthlyCharge', 'TotalServices']].head(10))

    IsNewCustomer  IsLongTermCustomer  AvgMonthlyCharge  TotalServices
0               1                   0         51.457500              1
1               1                   0         15.433333              2
2               0                   0         41.638605              4
3               0                   0         73.209756              2
4               0                   0         21.136667              3
5               0                   0         35.270526              2
6               0                   0         64.875000              1
7               0                   0         74.055882              1
8               1                   0         55.594286              2
10              0                   0         46.582105              1

In [66]:
df.to_csv("telco_customer_data_cleaned.csv", index=False)
print(" dataset cleaned !")

 dataset cleaned !

Total Charge  outlier (--

In [67]:
print("Before ")
print(f"Negtive Numbers  {(df['TotalCharges'] < 0).sum()}")
print(df[df['TotalCharges'] < 0][['tenure', 'MonthlyCharges', 'TotalCharges']].head())

negative_mask = df['TotalCharges'] < 0
df.loc[negative_mask, 'TotalCharges'] = (
    df.loc[negative_mask, 'tenure'] *
    df.loc[negative_mask, 'MonthlyCharges']
)

print("After Fix ")
print(f" Negtive Numbers : {(df['TotalCharges'] < 0).sum()}")
print(f"Min TotalCharges: {df['TotalCharges'].min()}")

Before
Negtive Numbers  195
      tenure  MonthlyCharges  TotalCharges
137     32.0           56.57        -64.03
237     14.0           48.92        -80.77
701      3.0          115.74        -22.32
749     12.0           44.17        -98.28
1250     6.0           27.50        -39.63
After Fix
 Negtive Numbers : 0
Min TotalCharges: 0.0

In [68]:
df.to_csv("telco_customer_data.csv", index=False)

In [69]:
df.dtypes

customerID                                  object
gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                     float64
PhoneService                                 int64
MultipleLines                                int64
InternetService                              int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
Contract                                     int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                        int64
HasInternet                                  int64
PaymentMethod_Bank transfer (automatic)       bool
PaymentMethod_Credit card (automatic)         bool
PaymentMethod_Electronic check                bool
PaymentMethod_Mailed check                    bool
IsNewCustomer                                int64
IsLongTermCustomer                           int64
AvgMonthlyCharge                           float64
TotalServices                                int64
dtype: object

In [70]:
df.isna().sum().sort_values(ascending=False)

customerID                                 0
gender                                     0
SeniorCitizen                              0
Partner                                    0
Dependents                                 0
tenure                                     0
PhoneService                               0
MultipleLines                              0
InternetService                            0
OnlineSecurity                             0
OnlineBackup                               0
DeviceProtection                           0
TechSupport                                0
StreamingTV                                0
StreamingMovies                            0
Contract                                   0
PaperlessBilling                           0
MonthlyCharges                             0
TotalCharges                               0
Churn                                      0
HasInternet                                0
PaymentMethod_Bank transfer (automatic)    0
PaymentMethod_Credit card (automatic)      0
PaymentMethod_Electronic check             0
PaymentMethod_Mailed check                 0
IsNewCustomer                              0
IsLongTermCustomer                         0
AvgMonthlyCharge                           0
TotalServices                              0
dtype: int64

In [71]:
df = df.drop(columns=["customerID"])

In [72]:
df.dtypes

gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                     float64
PhoneService                                 int64
MultipleLines                                int64
InternetService                              int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
Contract                                     int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                        int64
HasInternet                                  int64
PaymentMethod_Bank transfer (automatic)       bool
PaymentMethod_Credit card (automatic)         bool
PaymentMethod_Electronic check                bool
PaymentMethod_Mailed check                    bool
IsNewCustomer                                int64
IsLongTermCustomer                           int64
AvgMonthlyCharge                           float64
TotalServices                                int64
dtype: object

in notbook 2 we noticed that there are a - values in AvgMonthlyCharge

In [73]:
(df["AvgMonthlyCharge"] < 0).sum()

np.int64(195)

In [74]:
df[df["AvgMonthlyCharge"] < 0]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,Churn,HasInternet,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,IsNewCustomer,IsLongTermCustomer,AvgMonthlyCharge,TotalServices
137,1,0,0,0,32.0,1,2,2,1,0,...,0,1,True,False,False,False,0,0,-1.940303,2
237,1,1,0,0,14.0,1,2,2,0,0,...,0,1,False,True,False,False,0,0,-5.384667,3
701,0,0,0,1,3.0,1,2,1,0,0,...,0,1,True,False,False,False,1,0,-5.580000,1
749,0,0,1,0,12.0,1,2,2,1,1,...,1,1,False,False,True,False,0,0,-7.560000,5
1250,0,1,0,0,6.0,1,1,2,0,1,...,0,1,True,False,False,False,1,0,-5.661429,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68026,1,0,1,0,47.0,1,2,2,0,0,...,0,1,False,False,False,True,0,0,-2.028750,1
68158,0,0,1,0,10.0,1,1,1,0,0,...,0,1,False,False,True,False,0,0,-2.175455,1
69333,0,0,0,0,56.0,1,1,1,0,0,...,1,1,False,True,False,False,0,1,-1.015088,1
69871,0,0,1,0,31.0,1,1,1,0,0,...,1,1,False,True,False,False,0,0,-2.299375,3
69977,0,0,1,0,13.0,0,0,2,0,0,...,0,1,False,False,True,False,0,0,-5.810714,1

In [75]:
df["TotalCharges"].describe()

count    67376.000000
mean      1119.984806
std       1046.313623
min          0.000000
25%        395.835000
50%        820.430000
75%       1497.760000
max       8459.280000
Name: TotalCharges, dtype: float64

In [76]:
df["tenure"].describe()

count    67376.000000
mean        22.918428
std         15.276531
min          1.000000
25%         10.000000
50%         20.000000
75%         34.000000
max         72.000000
Name: tenure, dtype: float64

In [77]:
df["AvgMonthlyCharge"] = df["TotalCharges"] / (df["tenure"] + 1)

In [78]:
df["AvgMonthlyCharge"].describe()

count    67376.000000
mean        44.863760
std         24.864617
min          0.000000
25%         26.671684
50%         37.477337
75%         55.335121
max        116.351250
Name: AvgMonthlyCharge, dtype: float64

In [79]:
df[df["AvgMonthlyCharge"] < 0]

Empty DataFrame
Columns: [gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, MonthlyCharges, TotalCharges, Churn, HasInternet, PaymentMethod_Bank transfer (automatic), PaymentMethod_Credit card (automatic), PaymentMethod_Electronic check, PaymentMethod_Mailed check, IsNewCustomer, IsLongTermCustomer, AvgMonthlyCharge, TotalServices]
Index: []

[0 rows x 28 columns]

rename payment methods

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67376 entries, 0 to 69999
Data columns (total 28 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   67376 non-null  int64
 1   SeniorCitizen                            67376 non-null  int64
 2   Partner                                  67376 non-null  int64
 3   Dependents                               67376 non-null  int64
 4   tenure                                   67376 non-null  float64
 5   PhoneService                             67376 non-null  int64
 6   MultipleLines                            67376 non-null  int64
 7   InternetService                          67376 non-null  int64
 8   OnlineSecurity                           67376 non-null  int64
 9   OnlineBackup                             67376 non-null  int64
 10  DeviceProtection                         67376 non-null  int64
 11  TechSupport                              67376 non-null  int64
 12  StreamingTV                              67376 non-null  int64
 13  StreamingMovies                          67376 non-null  int64
 14  Contract                                 67376 non-null  int64
 15  PaperlessBilling                         67376 non-null  int64
 16  MonthlyCharges                           67376 non-null  float64
 17  TotalCharges                             67376 non-null  float64
 18  Churn                                    67376 non-null  int64
 19  HasInternet                              67376 non-null  int64
 20  PaymentMethod_Bank transfer (automatic)  67376 non-null  bool
 21  PaymentMethod_Credit card (automatic)    67376 non-null  bool
 22  PaymentMethod_Electronic check           67376 non-null  bool
 23  PaymentMethod_Mailed check               67376 non-null  bool
 24  IsNewCustomer                            67376 non-null  int64
 25  IsLongTermCustomer                       67376 non-null  int64
 26  AvgMonthlyCharge                         67376 non-null  float64
 27  TotalServices                            67376 non-null  int64
dtypes: bool(4), float64(4), int64(20)
memory usage: 13.1 MB

**Solved !**

In [81]:
df.to_csv("telco_customer_data_cleaned.csv", index=False)

# **Great work my team!**
**the cleaned dataset uploaded to the github repository:**