<a href="https://colab.research.google.com/github/linda-bsharat/telco-customer-churn-prediction/blob/main/notebooks/01_data_cleaning_and_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#////////////////////////////////////
# Importing LIB
#///////////////////////////////////


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#////////////////////////////////////
# importing data
#///////////////////////////////////



url = "https://raw.githubusercontent.com/linda-bsharat/telco-customer-churn-prediction/main/data/telco_customer_data_v2.csv"
df = pd.read_csv(url)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST00001,Male,0,No,Yes,3.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,68.61,205.83,Yes
1,CUST00002,Male,1,Yes,No,2.0,Yes,Yes,DSL,No,...,No internet service,Yes,NaN,No,One year,Yes,Bank transfer (automatic),23.15,46.3,No
2,CUST00003,Female,No,No,No,42.0,Yes,Yes,DSL,No,...,No,NaN,Yes,Yes,Month-to-month,No,Electronic check,42.63,1790.46,Yes
3,CUST00004,Female,0,No,Yes,40.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,No internet service,Month-to-month,No,Electronic check,75.04,3001.6,No
4,CUST00005,Male,Yes,Yes,Yes,17.0,Yes,NaN,Fiber optic,Yes,...,Yes,No,No internet service,No,Two year,Yes,Electronic check,22.38,380.46,Yes

part 1: fix the missing values

In [3]:
df.isna().sum().sort_values(ascending=False).head(15)

PaymentMethod       3569
Dependents          3565
Partner             3530
OnlineSecurity      2922
DeviceProtection    2894
StreamingTV         2827
StreamingMovies     2785
OnlineBackup        2747
TechSupport         2733
MultipleLines       1868
TotalCharges        1062
gender               748
SeniorCitizen        659
tenure               567
MonthlyCharges       388
dtype: int64

In [4]:
# =========================
# Handle Missing Values
# =========================

# yes/no service columns
service_cols = [
    "Dependents",
    "Partner",
    "OnlineSecurity",
    "DeviceProtection",
    "StreamingTV",
    "StreamingMovies",
    "OnlineBackup",
    "TechSupport",
    "MultipleLines",
]

df[service_cols] = df[service_cols].fillna("No")

In [5]:
df.isna().sum().sort_values(ascending=False).head(15)

PaymentMethod       3569
TotalCharges        1062
gender               748
SeniorCitizen        659
tenure               567
MonthlyCharges       388
Dependents             0
customerID             0
Partner                0
OnlineSecurity         0
PhoneService           0
MultipleLines          0
InternetService        0
TechSupport            0
DeviceProtection       0
dtype: int64

In [6]:
# =========================
# Fix TotalCharges type
# =========================

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# =========================
# Handle numeric missing (tenure, MonthlyCharges)
# =========================

df["tenure"] = df["tenure"].fillna(df["tenure"].median())
df["MonthlyCharges"] = df["MonthlyCharges"].fillna(df["MonthlyCharges"].median())

# =========================
# Impute TotalCharges using tenure * MonthlyCharges
# =========================

mask = df["TotalCharges"].isna()

df.loc[mask, "TotalCharges"] = (
    df.loc[mask, "tenure"] * df.loc[mask, "MonthlyCharges"]
)

In [7]:
df.isna().sum().sort_values(ascending=False)

PaymentMethod       3569
gender               748
SeniorCitizen        659
Partner                0
customerID             0
Dependents             0
tenure                 0
MultipleLines          0
PhoneService           0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
InternetService        0
TechSupport            0
StreamingTV            0
Contract               0
StreamingMovies        0
PaperlessBilling       0
MonthlyCharges         0
TotalCharges           0
Churn                  0
dtype: int64

In [8]:
# =========================
# Handle demographic missing values
# =========================

df["gender"] = df["gender"].fillna(df["gender"].mode()[0])
df["SeniorCitizen"] = df["SeniorCitizen"].fillna(df["SeniorCitizen"].mode()[0])

In [9]:
df.isna().sum().sort_values(ascending=False).head(3)

PaymentMethod    3569
gender              0
SeniorCitizen       0
dtype: int64

In [10]:
df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             27841
Bank transfer (automatic)    14102
Mailed check                 13963
Credit card (automatic)      10400
BANK TRANSFER                  125
Name: count, dtype: int64

In [11]:
df[df["PaymentMethod"].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
88,CUST00089,Female,1,No,No,14.0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,NaN,37.44,524.16,Yes
90,CUST00091,Male,0,No,No,22.0,Yes,No,DSL,No,...,No,No,No internet service,No,Month-to-month,Yes,NaN,41.19,906.18,Yes
109,CUST00110,FEMALE,No,No,No,11.0,Yes,Yes,DSL,No,...,No internet service,No,No,No internet service,Two year,Yes,NaN,18.39,202.29,No
113,CUST00114,Female,0,Yes,Yes,21.0,No,No phone service,Fiber optic,No,...,No,No,No,No,Two year,No,NaN,25.91,544.11,No
159,CUST00160,Male,0,No,Yes,10.0,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,NaN,29.91,299.10,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69874,CUST69875,Male,0,No,Yes,18.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,One year,Yes,NaN,41.19,741.42,No
69901,CUST69902,Female,0,No,Yes,30.0,Yes,No,DSL,No,...,No,No,No,No,Two year,No,NaN,46.09,1382.70,No
69933,CUST69934,Female,No,Yes,Yes,35.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,NaN,41.19,1441.65,No
69936,CUST69937,Male,0,No,No,7.0,Yes,No,DSL,No,...,Yes,No,No,No,One year,Yes,NaN,29.43,206.01,Yes
69937,CUST69938,Female,1,No,No,23.0,Yes,No,Fiber optic,No,...,Yes,No internet service,No,No,Month-to-month,No,NaN,25.20,579.60,Yes

In [12]:
# =========================
# Handle PaymentMethod missing values
# =========================

df["PaymentMethod"] = df["PaymentMethod"].fillna(df["PaymentMethod"].mode()[0])

In [13]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [14]:

df['gender'] = df['gender'].str.strip().str.capitalize()
df['gender'] = df['gender'].replace({'F': 'Female', 'M': 'Male'})
df['gender'] = df['gender'].replace({ 'Man': 'Male'})

In [15]:
df["gender"].value_counts()

gender
Female    35535
Male      34465
Name: count, dtype: int64

In [16]:
df["SeniorCitizen"] = df["SeniorCitizen"].replace({
    "Yes": 1,
    "No": 0,
    "not senior": 0})
df["SeniorCitizen"] = df["SeniorCitizen"].astype(int)

In [17]:
df["SeniorCitizen"].value_counts()

SeniorCitizen
0    56053
1    13947
Name: count, dtype: int64

In [18]:
df["Churn"].value_counts()

Churn
No          37057
Yes         32713
Unknown        54
CHURNED        46
N              46
NO CHURN       45
Y              39
Name: count, dtype: int64

In [19]:

pd.set_option('future.no_silent_downcasting', True)

df['Churn'] = df['Churn'].replace({
    'Yes': 1, 'Y': 1, 'CHURNED': 1,
    'No': 0, 'N': 0, 'NO CHURN': 0,
    'Unknown': None
})
df = df.dropna(subset=['Churn'])
df['Churn'] = df['Churn'].astype(int)

In [20]:
df["Churn"].value_counts()

Churn
0    37148
1    32798
Name: count, dtype: int64

In [21]:
df.to_csv("telco_customer_data_cleaned.csv", index=False)

In [22]:
# =========================
# Standardize PaymentMethod
# =========================

df['PaymentMethod'] = df['PaymentMethod'].replace({
    'BANK TRANSFER': 'Bank transfer (automatic)'
})

df['PaymentMethod'].value_counts()

PaymentMethod
Electronic check             31379
Bank transfer (automatic)    14215
Mailed check                 13959
Credit card (automatic)      10393
Name: count, dtype: int64

In [23]:
yes_no_columns = [
    'Partner',
    'Dependents',
    'PhoneService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'PaperlessBilling'
]

for col in yes_no_columns:
    print(f"{col} unique values:", df[col].unique())

Partner unique values: ['No' 'Yes']
Dependents unique values: ['Yes' 'No']
PhoneService unique values: ['Yes' 'No']
OnlineSecurity unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
OnlineBackup unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
DeviceProtection unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
TechSupport unique values: ['No internet service' 'Yes' 'No' 'Y' 'True']
StreamingTV unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
StreamingMovies unique values: ['No internet service' 'No' 'Yes' 'Y' 'True']
PaperlessBilling unique values: ['No' 'Yes']

In [24]:
df.replace(['Y', 'True'], 'Yes', inplace=True)

In [25]:
df.replace('No internet service', 'No', inplace=True)

In [26]:
yes_no_columns = [
    'Partner',
    'Dependents',
    'PhoneService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'PaperlessBilling'
]

for col in yes_no_columns:
    df[col] = df[col].fillna('No')

In [27]:
for col in yes_no_columns:
    print(col, df[col].unique())

Partner ['No' 'Yes']
Dependents ['Yes' 'No']
PhoneService ['Yes' 'No']
OnlineSecurity ['No' 'Yes']
OnlineBackup ['No' 'Yes']
DeviceProtection ['No' 'Yes']
TechSupport ['No' 'Yes']
StreamingTV ['No' 'Yes']
StreamingMovies ['No' 'Yes']
PaperlessBilling ['No' 'Yes']

In [28]:
for col in yes_no_columns:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [29]:
print(df[yes_no_columns].head())

   Partner  Dependents  PhoneService  OnlineSecurity  OnlineBackup  \
0        0           1             1               0             0
1        1           0             1               0             0
2        0           0             1               0             1
3        0           1             1               0             0
4        1           1             1               1             0

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0                 0            0            0                0
1                 0            1            0                0
2                 0            0            1                1
3                 1            0            0                0
4                 1            0            0                0

   PaperlessBilling
0                 0
1                 1
2                 0
3                 0
4                 1

In [30]:
print(df[yes_no_columns].dtypes)

Partner             int64
Dependents          int64
PhoneService        int64
OnlineSecurity      int64
OnlineBackup        int64
DeviceProtection    int64
TechSupport         int64
StreamingTV         int64
StreamingMovies     int64
PaperlessBilling    int64
dtype: object

## Problem **Here**

In [31]:
df['Churn'].value_counts()
df['Churn'].info()

<class 'pandas.core.series.Series'>
Index: 69946 entries, 0 to 69999
Series name: Churn
Non-Null Count  Dtype
--------------  -----
69946 non-null  int64
dtypes: int64(1)
memory usage: 1.1 MB

In [32]:
df['Churn'] = df['Churn'].replace({'Yes': 1, 'No': 0})

In [33]:
df['Churn'].value_counts()
df['Churn'].info()

<class 'pandas.core.series.Series'>
Index: 69946 entries, 0 to 69999
Series name: Churn
Non-Null Count  Dtype
--------------  -----
69946 non-null  int64
dtypes: int64(1)
memory usage: 1.1 MB

In [34]:
print(df[yes_no_columns].isnull().sum())

Partner             0
Dependents          0
PhoneService        0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
PaperlessBilling    0
dtype: int64

In [35]:
df.select_dtypes(include='object').columns

Index(['customerID', 'gender', 'MultipleLines', 'InternetService', 'Contract',
       'PaymentMethod'],
      dtype='object')

In [36]:
for col in df.select_dtypes(include='object').columns:
    print("Column:", col)
    print(df[col].unique())
    print("-"*50)

Column: customerID
['CUST00001' 'CUST00002' 'CUST00003' ... 'CUST69998' 'CUST69999'
 'CUST70000']
--------------------------------------------------
Column: gender
['Male' 'Female']
--------------------------------------------------
Column: MultipleLines
['Yes' 'No' 'No phone service']
--------------------------------------------------
Column: InternetService
['No' 'DSL' 'Fiber optic']
--------------------------------------------------
Column: Contract
['Month-to-month' 'One year' 'Two year' 'M-M']
--------------------------------------------------
Column: PaymentMethod
['Mailed check' 'Bank transfer (automatic)' 'Electronic check'
 'Credit card (automatic)']
--------------------------------------------------

In [37]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [38]:
df['gender'] = df['gender'].str.strip().str.capitalize()
df['gender'] = df['gender'].replace({'F': 'Female', 'M': 'Male'})
df['gender'] = df['gender'].replace({ 'Man': 'Male'})

In [39]:
df['gender'] = df['gender'].replace('nan', None)
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

In [40]:
print(df['gender'].isnull().sum())

0

In [41]:
print(df['gender'].unique())

['Male' 'Female']

In [42]:
df['gender'] = df['gender'].map({'Male':1, 'Female':0})

In [43]:
print("Unique values:", df['gender'].unique())
print("Missing values:", df['gender'].isnull().sum())
print("Data type:", df['gender'].dtype)

Unique values: [1 0]
Missing values: 0
Data type: int64

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69946 entries, 0 to 69999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        69946 non-null  object
 1   gender            69946 non-null  int64
 2   SeniorCitizen     69946 non-null  int64
 3   Partner           69946 non-null  int64
 4   Dependents        69946 non-null  int64
 5   tenure            69946 non-null  float64
 6   PhoneService      69946 non-null  int64
 7   MultipleLines     69946 non-null  object
 8   InternetService   69946 non-null  object
 9   OnlineSecurity    69946 non-null  int64
 10  OnlineBackup      69946 non-null  int64
 11  DeviceProtection  69946 non-null  int64
 12  TechSupport       69946 non-null  int64
 13  StreamingTV       69946 non-null  int64
 14  StreamingMovies   69946 non-null  int64
 15  Contract          69946 non-null  object
 16  PaperlessBilling  69946 non-null  int64
 17  PaymentMethod     69946 non-null  object
 18  MonthlyCharges    69946 non-null  float64
 19  TotalCharges      69946 non-null  float64
 20  Churn             69946 non-null  int64
dtypes: float64(3), int64(13), object(5)
memory usage: 11.7+ MB

# **Fixing the multiple lines values                    // Qassam**

In [61]:
df["MultipleLines"].value_counts()

MultipleLines
Yes                 34660
No                  28353
No phone service     6933
Name: count, dtype: int64

In [70]:
df[(df["PhoneService"] == 1) &
   (df["MultipleLines"] == "No phone service")].shape

(0, 21)

In [59]:
mask = (df['PhoneService'] == 1) & (df['MultipleLines'] == 'No phone service')
df.loc[mask, 'MultipleLines'] = 'No'
print(f'Fixed {mask.sum()} inconsistent rows')

Fixed 1320 inconsistent rows

In [60]:
print(df['MultipleLines'].value_counts())

MultipleLines
Yes                 34660
No                  28353
No phone service     6933
Name: count, dtype: int64

# success ///////////QASSAM

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69946 entries, 0 to 69999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        69946 non-null  object
 1   gender            69946 non-null  int64
 2   SeniorCitizen     69946 non-null  int64
 3   Partner           69946 non-null  int64
 4   Dependents        69946 non-null  int64
 5   tenure            69946 non-null  float64
 6   PhoneService      69946 non-null  int64
 7   MultipleLines     69946 non-null  object
 8   InternetService   69946 non-null  object
 9   OnlineSecurity    69946 non-null  int64
 10  OnlineBackup      69946 non-null  int64
 11  DeviceProtection  69946 non-null  int64
 12  TechSupport       69946 non-null  int64
 13  StreamingTV       69946 non-null  int64
 14  StreamingMovies   69946 non-null  int64
 15  Contract          69946 non-null  object
 16  PaperlessBilling  69946 non-null  int64
 17  PaymentMethod     69946 non-null  object
 18  MonthlyCharges    69946 non-null  float64
 19  TotalCharges      69946 non-null  float64
 20  Churn             69946 non-null  int64
dtypes: float64(3), int64(13), object(5)
memory usage: 11.7+ MB

In [63]:
df["InternetService"].value_counts()

InternetService
Fiber optic    38470
DSL            17579
No             13897
Name: count, dtype: int64

In [64]:
df["MultipleLines"].value_counts()

MultipleLines
Yes                 34660
No                  28353
No phone service     6933
Name: count, dtype: int64

In [68]:
df["Contract"].value_counts()

Contract
Month-to-month    41980
One year          14005
Two year          13961
Name: count, dtype: int64

In [66]:
df["Contract"] = df["Contract"].replace({
    "M-M": "Month-to-month"
})

# Verify
print(df["Contract"].value_counts())

Contract
Month-to-month    41980
One year          14005
Two year          13961
Name: count, dtype: int64

# **Feature Engineering**

In [71]:
df["HasInternet"] = (df["InternetService"] != 0).astype(int)

In [72]:
df["HasInternet"].value_counts()

HasInternet
1    69946
Name: count, dtype: int64

In [74]:
df.to_csv("telco_customer_data_cleaned.csv", index=False)